exclude_files = {
    "libs/**/*.lua",
}
read_globals = {
    -- api functions
    "CastSpellByID",
    "GetLocale",
    "GetCraftDisplaySkillLine",
    "GetCraftInfo",
    "GetNumCrafts",
    "GetMoney",
    "GetFileIDFromPath",
    "GetSpellInfo",
    "GetSpellSubtext",
    "GetQuestDifficultyColor",
    "InCombatLockdown",
    "IsSpellKnown",
    "IsPetActive",
    "IsPlayerSpell",
    "IsShiftKeyDown",
    "UnitClass",
    "UnitLevel",
    "UnitRace",
    "UnitFactionGroup",
    "FauxScrollFrame_Update",
    "FauxScrollFrame_GetOffset",
    "FauxScrollFrame_OnVerticalScroll",
    "CreateFrame",
    "CreateColor",
    "PlaySound",
    "EasyMenu",
    "GetMerchantItemLink",
    "GetMerchantNumItems",
    "GetMerchantItemID",
    "UnitCreatureFamily",
    "UnitCreatureType",
    "UnitGUID",
    "RunNextFrame",
    "SetItemButtonNameFrameVertexColor",
    "SetItemButtonSlotVertexColor",
    "SetItemButtonTextureVertexColor",
    "SetItemButtonNormalTextureVertexColor",
    "ShowAllSpellRanksCheckbox",
    "SpellBookPageText",
    "ToggleSpellBook",
    "GetInventoryItemTexture",
    "SpellBookPrevPageButton",
    "SpellBookNextPageButton",
    -- function aliases
    "tinsert",
    "format",
    "hooksecurefunc",
    "foreachi",
    "wipe",
    "sort",
    "strlower",
    "strfind",
    "strsplit",
    -- api classes
    "Spell",
    "Item",
    "MenuUtil",
    "EventUtil",
    -- blizzard frames
    "UIParent",
    "MerchantFrame",
    "GameTooltip",
    "SkillFrame",
    "PlayerSpellsFrame",
    "PlayerSpellsUtil",
    -- frame methods
    "SearchBoxTemplate_OnTextChanged",
    "ChatEdit_GetActiveWindow",
    "ChatFrame_OpenChat",
    -- namespaces
    "C_AddOns",
    "C_Timer",
    "C_Spell",
    "C_CurrencyInfo",
    "C_SpellBook",
    -- enums
    "MenuResponse",
    "Enum",
    -- constants
    "MERCHANT_ITEMS_PER_PAGE",
    "SPELL_REQUIRED_FORM",
    "ITEM_SPELL_KNOWN",
    "SOUNDKIT",
    "GREEN_FONT_COLOR_CODE",
    "ORANGE_FONT_COLOR_CODE",
    "RED_FONT_COLOR_CODE",
    "LIGHTYELLOW_FONT_COLOR_CODE",
    "GRAY_FONT_COLOR_CODE",
    "LIGHTYELLOW_FONT_COLOR",
    "GREEN_FONT_COLOR",
    "NORMAL_FONT_COLOR",
    "GRAY_FONT_COLOR",
    "RED_FONT_COLOR",
    "BACKDROP_DIALOG_32_32",
    "DONE",
    "C_Map",
    "FONT_COLOR_CODE_CLOSE",
    "HIGHLIGHT_FONT_COLOR_CODE",
    "PARENS_TEMPLATE",
    "MAX_SKILLLINE_TABS",
    "SKILLS_TO_DISPLAY",
    "BOOKTYPE_SPELL",
    "UISpecialFrames",
    "ERR_LEARN_SPELL_S",
    "WHITE_FONT_COLOR",
    "WOW_PROJECT_ID",
    "WOW_PROJECT_BURNING_CRUSADE_CLASSIC",

    -- my other addons
    "HookCTPUpdate",

    -- libs
    "LibStub",
}
globals = {
    -- blzzard frames
    "SpellBookFrame",

    -- my other addons
    "ClassTrainerPlusDBPC",
    "CTP_UpdateService",

    "WhatsTrainingFrame",
    "WT_NeedsToOpenBeastTraining",
    "WT_LearnedPetAbilities",
    "WT_WeaponGrouping",
    "WT_IgnoredSpells"
}
