read_globals = {
  -- api functions
  "CastSpellByID",
  "GetLocale",
  "GetCoinTextureString",
  "GetCraftDisplaySkillLine",
  "GetCraftInfo",
  "GetNumCrafts",
  "GetMoney",
  "GetFileIDFromPath",
  "GetSpellInfo",
  "GetSpellSubtext",
  "GetQuestDifficultyColor",
  "IsSpellKnown",
  "IsPlayerSpell",
  "UnitClass",
  "UnitLevel",
  "UnitRace",
  "UnitFactionGroup",
  "FauxScrollFrame_Update",
  "FauxScrollFrame_GetOffset",
  "FauxScrollFrame_OnVerticalScroll",
  "CreateFrame",
  "PlaySound",
  "EasyMenu",
  "GetMerchantItemLink",
  "GetMerchantNumItems",
  "GetMerchantItemID",
  "UnitGUID",
  "SetItemButtonNameFrameVertexColor",
  "SetItemButtonSlotVertexColor",
  "SetItemButtonTextureVertexColor",
  "SetItemButtonNormalTextureVertexColor",
  -- function aliases
  "tinsert",
  "format",
  "hooksecurefunc",
  "foreachi",
  "wipe",
  "sort",
  "strsplit",
  -- api classes
  "Spell",
  "Item",
  -- blizzard frames
  "SpellBookFrame",
  "UIParent",
  "MerchantFrame",
  -- constants
  "MERCHANT_ITEMS_PER_PAGE",
  "SPELL_REQUIRED_FORM",
  "ITEM_SPELL_KNOWN",
  "SOUNDKIT",
  "GREEN_FONT_COLOR_CODE",
  "ORANGE_FONT_COLOR_CODE",
  "RED_FONT_COLOR_CODE",
  "LIGHTYELLOW_FONT_COLOR_CODE",
  "GRAY_FONT_COLOR_CODE",
  "FONT_COLOR_CODE_CLOSE",
  "HIGHLIGHT_FONT_COLOR_CODE",
  "PARENS_TEMPLATE",
  "MAX_SKILLLINE_TABS",
  "BOOKTYPE_SPELL",
  "ERR_LEARN_SPELL_S",

  "HookCTPUpdate"
}
globals = {
  "ClassTrainerPlusDBPC",
  "CTP_UpdateService",
  "WhatsTrainingFrame",
  "WT_NeedsToOpenBeastTraining",
  "WT_LearnedPetAbilities"
}